name: Deploy Next.js App

on:
  push:
    tags:
      - "v*" # Triggers on any tag that starts with 'v' (e.g., v1.0.0)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        env:
          HOST: ec2-44-210-93-62.compute-1.amazonaws.com
          USER: ec2-user
        run: |
          rsync -avz --exclude 'node_modules' --exclude '.git' ./ $USER@$HOST:/home/$USER/your-app-directory
          ssh $USER@$HOST "
            cd /home/$USER/your-app-directory &&
            npm install &&
            npm run build &&
            pm2 start npm --name \"your-app-name\" -- start
          "
